baseURL = "https://nandita-roy.github.io/"
locale = "en-us"
title = "Nandita Roy"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowShareButtons = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archives/"
    weight = 20
